site_name: 小寒文档中心
theme: 
  name: material
  language: 'zh'
extra:
  search:
    language: 'jp'
markdown_extensions:
  - meta
  - smarty
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 主页: index.md
  - 日常记录:
    - Linux:
      - 添加桌面快捷方式: notebook/linux/AddDesktopLink.md

